version: 0.2
phases:
  install:
    commands:
      - "npm install"
  build:
    commands:
      - "npm run build-ts"
artifacts:
  files:
    - index.js
    - dist/**/*
    - request-map.js
    - credentials.json
    - node_modules/**/*
